### ISSUE TITLE
AUR上的构建可以拆分软件包但本地的不行，是刻意设计吗

### ISSUE THREAD

**Issue by wszqkzqk** [vifly/arch-build#1]
本地的不能够按照PKGBUILD中的定义将分割软件包（如`linux`, `linux-header`, `linux-doc`）

**Comment by vifly** [comment]
可以提供一下报错信息吗，理论上是支持拆包的

**Comment by wszqkzqk** [comment]
> 可以提供一下报错信息吗，理论上是支持拆包的

我自己加了一句`pacman -S --noconfirm initramfs`就可以了，应该是默认环境没有依赖

**Comment by vifly** [comment]
> > 可以提供一下报错信息吗，理论上是支持拆包的
> 
> 我自己加了一句 `pacman -S --noconfirm initramfs` 就可以了，应该是默认环境没有依赖

你需要在 PKGBUILD 的全局依赖或者全局构建依赖（makedepends）加上缺失的依赖，相关讨论见 https://github.com/Jguer/yay/issues/1013#issuecomment-527216969
