### ISSUE TITLE
[Feature Request] Use github release as repo link

### ISSUE THREAD

**Issue by vanbwodonk** [vifly/arch-build#7]
Hi, Thanks for very good AUR repo implementation. Could you consider to use github release as arch repo? Use github release as arch repo is possible. Need to upload *.db into release too. See this as example https://github.com/LizardByte/pacman-repo.

**Comment by vifly** [comment]
Thanks for your suggestion. You are right, just need to upload Arch DB file, and update README to explain how to use it. I will implement it soon.

**Comment by vifly** [comment]
Fix in https://github.com/vifly/arch-build/commit/490c9da873873d3ec2baed128fc2ff1f7c982ddc and https://github.com/vifly/arch-build/commit/41aa30e2600368867ac8159f9c8bc36784deaa8c. I'm closing this issue now. If you encounter any further problems, feel free to reopen it or create a new issue.
